# ==============================================================
# = Authentication Server JWT
# = PROFILO GIT
# ==============================================================

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: file:///home/nicola/Documents/git-config-repository
          
# ==============================================================
# = Actuator Info
# ==============================================================
info:
  assistenza:
    nome: "Nicola La Rocca"
  nome:
    nome-app: "Config-Server"
    profilo: "GIT"